config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hotels
  root 'welcome#index'
  root to: "home#index"
  resources :hotels do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :reviews
  validates :name, :star, :descr, :photo, :addr1,
            :addr2, :addr3, :addr4, :rate, :price, presence: true
  mount_uploader :photo, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = Hotel.all.paginate(page: params[:page], per_page: 6)
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.rate = 0
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def update
    @hotel = Hotel.find(params[:id])

    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])

    @hotel.reviews.each(&:destroy)
    @hotel.destroy

    redirect_to hotels_path
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :star, :breakf,
                                  :descr, :photo, :addr1, :addr2, :addr3, :addr4, :rate, :price)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @review = @hotel.reviews.create(review_params)
    rate = 0
    @hotel.reviews.each do |r|
      rate += r.rate
    end
    rate /= @hotel.reviews.count.to_f
    @hotel.rate = eval(format("%.2f", rate))
    @hotel.save
    redirect_to hotel_path(@hotel)
  end

  private

  def review_params
    params.require(:review).permit(:name, :descr, :rate)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @hotels = Hotel.order('rate DESC LIMIT 5')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotels/_form.html.erb
<%= form_with model: @hotel, :html => {:multipart => true}, local: true do |form| %>
 
  
  <div class="form-border">
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

    
    <p>
	    <%= form.label :breakf %><br>
	    <%= form.radio_button :breakf, true, :checked => true %>yes
	    <%= form.radio_button :breakf, false %>no
	</p>
	


    <p>
    	<%= form.label :star, 'Level of hotel' %><br>
    	<%= form.select(:star, options_for_select([['1 star', 2],['2 star', 3],['3 star', 4],['4 star', 5],['5 star', 6],])) %>
    </p>


  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :descr %>
  </p>

  <p>
    <%= form.file_field :photo %>   
  </p>
 
  <p>
    <%= form.label 'Country:' %><br>
    <%= form.text_field :addr1 %>
  </p>

  <p>
    <%= form.label 'State: ' %><br>
    <%= form.text_field :addr2 %>
  </p>

  <p>
    <%= form.label 'City: ' %><br>
    <%= form.text_field :addr3 %>
  </p>

  <p>
    <%= form.label 'Street: ' %><br>
    <%= form.text_field :addr4 %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>  
  </p>
  <div>
    <%= form.submit "Create Hotel", :class=> "dis-but-grey", :disabled => true %>
  </div>

  </div>
  <% if @hotel.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@hotel.errors.count, "error") %> prohibited
      this hotel from being saved:
    </h2>
    <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  
<% end %>

app/views/hotels/edit.html.erb
<%= render 'welcome/menu' %> 

<% if user_signed_in?%>
	<h2>Editing hotel</h2>
	<%= render 'form' %>
<% else %>
	<%= render 'welcome/needSignIn' %>
<% end %> 

<%= link_to 'Back', hotels_path %>
<%= render 'welcome/footer' %>

app/views/hotels/index.html.erb
<%= render 'welcome/menu' %>
<div class="container ">

    <h2 class = "align-top5">Hotel's list</h2>
    <div class="test-flex">
        <% @hotels.each do |hotel| %>
          <div class = "hotel">
          <div class = "fix-text" style="margin-left: 60%;">
              <h2><%= link_to hotel.name, hotel_path(hotel) %></h2>
                <% if hotel.star == 5%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 4%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 3%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 2%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 1%>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
              <% if hotel.breakf == "true"%>
          <h3>Breakf: Yes</h3>
          <%else%>
          <h3>Breakfast: No</h3>
          <%end%>
              <h3>Description:</h3>
              <div class="prokrutka">
                 <%= hotel.descr %>
              </div>
              <h3>Adress: <%= hotel.addr1 + ', ' +hotel.addr2 + ', '+hotel.addr3 + ', ' + hotel.addr4 %></h3>
              <h3>Price: <%= hotel.price %></h3>
              <h3>User rate:</h3> 
       <% if hotel.rate == 5%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 4%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 3%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 2%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 1%>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
              <p><%= link_to 'Show', hotel_path(hotel) %></p>
            </div>
              
            <%= image_tag hotel.photo_url().to_s, :class => "style_image"%>
          </div>
        <% end %>
        </div>
    <%= will_paginate @hotels , previous_label: '-', next_label: '+', inner_window:1, outer_window: 0%>
</div>

<%= render 'welcome/footer' %>

app/views/hotels/new.html.erb
<%= render 'welcome/menu' %>
<div class="container">


	<% if user_signed_in?%>
		<h2 class="align-top5">New Hotel </h2>
	
		
			<%= render 'form' %>
		<% else %>
			<%= render 'welcome/needSignIn' %>
		<% end %>
		
		
	
</div>
<%= render 'welcome/footer' %>

app/views/hotels/show.html.erb
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<%= render 'welcome/menu' %>

<div class = "big_banner">
<h2 align="center" style="padding-top: 3%"><%= @hotel.name %> </h2>
  <div class = "hotel" style="margin-top: 3%">
    <section id="big_img">
      <article>
        <a>
          <figure>
            <%= image_tag @hotel.photo_url().to_s%>
            <figcaption>
              <header> User rate </header>
              <div class="fix-text" style="margin-top: 20px">
              <img src="/images/star.png">
          <h4><%= @hotel.rate %></h4>
          </div>
          <div class="fix-text" style="margin-top: 2vw; margin-left: 15vw">
          <% if @hotel.breakf == "true"%>
          <h3>Breakf: Yes</h3>
          <%else%>
          <h3>Breakfast: No</h3>
          <%end%>
          <h3>hotel level: <%= @hotel.star %></h3>
       </div>
       <div>
       <h3 style="margin-top: 12vw; margin-left: -1vw">Description: </h3>

       </div>
       <div class="d">
       <%= @hotel.descr %>
       </div>
            </figcaption>
          </figure>
        </a>
      </article>
    </section>
        <div class="fix-text-show">
        <div class="clearfix">
        <% if user_signed_in? %>
         <h2>Add a comment:</h2>
         <%= form_with(model: [ @hotel, @hotel.reviews.build ], local: true) do |form| %>
         <p>
         <%= form.label :name, 'Write your name' %><br>
         <%= form.text_field :name %>
         </p>
         <p>
          <%= form.label :descr, 'Write your comment' %><br>
          <%= form.text_area :descr %>
        </p>
      <p>
      <%= form.label :rate, 'Level of hotel' %><br>
</p>
<fieldset class="rating">
    <legend>Please rate:</legend>
     <%= form.radio_button :rate, 5, :class => "rating", :id => "star5"%><label for="star5" title="Excelent!">5 stars</label>
     <%= form.radio_button :rate, 4, :class => "rating", :id => "star4"%><label for="star4" title="Good">4 stars</label>
     <%= form.radio_button :rate, 3, :class => "rating", :id => "star3"%><label for="star3" title="normal">3 stars</label>
     <%= form.radio_button :rate, 2, :class => "rating", :id => "star2"%><label for="star2" title="bad">2 stars</label>
     <%= form.radio_button :rate, 1, :class => "rating", :id => "star1"%><label for="star1" title="Very bad">1 star</label>

</fieldset>
<div style="margin-top: 90px">
      </p><br>
      <p>
      <div class="g-recaptcha" data-sitekey="6LcaF2IUAAAAAPR1Kq6Grr6CbcdhEBg5puLJB8V1"></div>
      </p>
</div>

<div class="nice-hrefs"> 
<p><%= link_to 'Back', hotels_path %></p>
<p><%= form.submit %></p>
</div>
<% end %>
<%else%>
<h2>Please sign in for review this hotel</h2>
<%end%>
</div>

</div>
</div>


</div>
     <div style="margin-top: 2vw; margin-left: 15vw; height: 100%">
    <% if @hotel.reviews.count === 0 %>

    <h2>No reviews</h2>
  <%else%>

    <h2>Reviews</h2>
<%end%>
</div>

  <% @hotel.reviews.each do |r| %>
  <div class="comment">
  <p>
    <strong>Commenter:</strong>
    <%= r.name %>
  </p>
  <p>
    <strong>Rate:</strong>
    <% if r.rate == 5%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if r.rate == 4%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if r.rate == 3%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if r.rate == 2%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if r.rate == 1%>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
  </p>
  <p>
    <strong>Description:</strong>
    <%= r.descr %>
  </p>
</div>
<% end %>

<%= render 'welcome/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello Hotel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <div class="alert">
        <%= alert %>
       </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/_footer.html.erb
<footer class="main" style="margin-top: 20%; width: 100%;">
	<div class="container clearfix">
		<div id="uncopyright">
		<p>Uncopyright &copy; 2018 <strong>Team: trains. For JetRuby</strong></p>
		</div>
		<div id="credits">
		<p>Sustainabily coded with love by <a href="http://vk.com/">Igor, Egor, Vitalli, Yana</a></p> 
		</div>
	</div>
</footer>  

app/views/welcome/_menu.html.erb
<!DOCTYPE html>
<html>
<head>
<script src='https://www.google.com/recaptcha/api.js'></script>
<% content_for :title, "Hello Hotel"%>
</head>

<body>

  <div class="container">
    <header class="main">
    
      <nav>
                <a href="<%= welcome_index_url %>"><%= image_tag("HH0.png", :id=> 'logo', :alt => "Logo") %></a>
        <ul>
          <li><%= link_to 'Main', welcome_index_url %></li>
          <li><%= link_to 'All hotels', hotels_url %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Add hotel', new_hotel_path %></li>
            <li><%= link_to current_user.email.to_s.split("@")[0] + ',  Sign out', destroy_user_session_path, method: :delete%></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          
          <% end %>
        </ul>
      </nav>
    </header>
  </div>

</body>
</html>

</div>

</body>
</html>

app/views/welcome/_needSignIn.html.erb
<h1>Sign in to perform this operation</h1>

app/views/welcome/_topFive.html.erb
      <div style="margin-top: 10px">
        <% @hotels.each do |hotel| %>
          <div class = "hotel">
          <div id = "description">
          <div class = "fix-text">
            <h2><%= link_to hotel.name, hotel_path(hotel) %></h2>
            <h3>Stars:</h3>
             <% if hotel.star == 5%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 4%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 3%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 2%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.star == 1%>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
             <% if hotel.breakf == "true"%>
          <h3>Breakf: Yes</h3>
          <%else%>
          <h3>Breakfast: No</h3>
          <%end%>
            <h3>Description:</h3>
            <div class="prokrutka">
                 <%= hotel.descr %>
              </div>
            <h3>Adress: <%= hotel.addr1 + ', ' +hotel.addr2 + ', '+hotel.addr3 + ', ' + hotel.addr4 %></h3>
            <h3>Price: <%= hotel.price %></h3>
            <h3>User rate:</h3> 
       <% if hotel.rate == 5%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 4%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 3%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 2%>
             <a><img src="/images/mini_star.png"></a>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
          <% if hotel.rate == 1%>
             <a><img src="/images/mini_star.png"></a>
             <%end%>
            </div>
            </div>

                <a href="<%= hotel_path(hotel) %>"><%= image_tag hotel.photo_url().to_s, :class => "style_image" %></a>
          </div>
        <% end %>
      </div>

app/views/welcome/index.html.erb
<script type="text/javascript">
	window.onload = function() { // запуск слайдера после загрузки документа
  slider.init();
  setInterval(function() { // ставим пятисекундный интервал для перелистывания картинок
    slider.right();
  },5000);
};
</script>


<%= render 'menu' %>

<div id="main">
  <button id="butt" class="left" onclick="slider.left();"><</button>
  <div id="scr">
  	<div id="st"></div>
  </div>
  <button id="butt" class="right" onclick="slider.right();">></button>
</div>
<h2 align="center" style="margin-top: 5%" class="article-h2">Top 5 best hotels</h2>
<%= render 'topFive'%>

<%= render 'footer' %>